# Generated by Django 5.1.4 on 2025-01-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='auth_image',
            field=models.ImageField(blank=True, null=True, upload_to='auth_blog/'),
        ),
    ]
