# Generated by Django 5.1.4 on 2025-01-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_auth_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='auth_image',
        ),
    ]
