# Generated by Django 5.1.4 on 2025-01-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Services/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Services/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
