# Generated by Django 5.1.4 on 2025-01-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_hover',
            field=models.ImageField(blank=True, null=True, upload_to='Services/'),
        ),
    ]
