# Generated by Django 5.1.4 on 2025-01-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_clientlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlogo',
            name='name',
        ),
    ]
