# Generated by Django 5.1.4 on 2025-01-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_whychooseus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Awards', 'Awards'), ('Certificate', 'Certificate')], default='Awards', max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='awards/')),
                ('description', models.TextField()),
            ],
        ),
    ]
