# Generated by Django 5.1.4 on 2025-01-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
