# Generated by Django 5.1.4 on 2025-01-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_brand_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='url',
            new_name='googlemap_url',
        ),
    ]
