"""
Django settings for ape project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$&%lo4sq5#k=r)(0thn#1=_#!9k_+@cxd@dcwqrw)b5jf#gbk4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'ckeditor',

    'home',
    'site_settings',
    'products',
    'about',
    'research',
    'contact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ape.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'site_settings.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'ape.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Global static folder
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Directory for collected static files (for deployment)


MEDIA_URL = '/media/'  # URL to access media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')  # Path to store media files

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER ='aravintharavinth6369@gmail.com'
EMAIL_HOST_PASSWORD ='qdqy zgpv lymv kbnm'
EMAIL_HOST_USER_NANE='SIPY'
ADMIN_EMAIL = 'hello@sipy.in'




CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
        'toolbar_Full': [
            ['Styles', 'Format', 'Font', 'FontSize'],  # Text styling
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],  # Text formatting
            ['TextColor', 'BGColor'],  # Text and background colors
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],  # Lists and indentation
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],  # Text alignment
            ['Link', 'Unlink', 'Anchor'],  # Hyperlink management
            ['Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak'],  # Media and layout
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord'],  # Clipboard functionality
            ['Undo', 'Redo'],  # Undo and redo
            ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt'],  # Editing tools
            ['RemoveFormat', 'Source'],  # Code and cleanup
            ['Maximize', 'ShowBlocks', '-', 'About'],  # View options
            ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'HiddenField'],  # Form elements
        ],
        'extraPlugins': ','.join([
            'colorbutton', 'justify', 'clipboard', 'table', 'image2', 'uploadimage',  # Additional plugins
        ]),
        'removePlugins': 'elementspath',  # Optional: Removes the element path bar
        'resize_enabled': True,  # Allows resizing of the editor window
    }
}



CRISPY_TEMPLATE_PACK = 'uni_form'

JAZZMIN_SETTINGS = {
    "site_title": "APE",  # Title of the admin site
    "site_header": "My Admin",  # Header displayed on the admin site
    "site_brand": "Website",  # Brand name displayed in the admin
    "welcome_sign": "Welcome to the Admin Panel!",  # Welcome message
    "show_ui_builder": True,  # Show UI builder for customization
    "changeform_format": "horizontal",  # Form layout (options: 'vertical', 'horizontal')
    "use_google_fonts": True,  # Whether to use Google Fonts
    # Add more options here based on your requirements
    
    "icons": {
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "site_settings.Brand": "fas fa-cogs",  # Custom icon for MyModel in your app
        "site_settings.Social_links": "fas fa-link",
        "home.HeroSection": "fas fa-home",
        "home.Service": "fas fa-hands-helping",
        "home.Awards": "fas fa-trophy",
    },
}
