# Generated by Django 5.1.4 on 2025-01-28 11:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_product_images/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('rated_capacity', models.CharField(max_length=255)),
                ('factory_model', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255, verbose_name='Dimensions (W*D*H,MM)')),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Weight (KG)')),
                ('packing_size', models.CharField(max_length=255, verbose_name='Packing Size (W*D*H,MM)')),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross Weight (KG)')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
    ]
